version: "3.1"
services:
  database:
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back-end


  savannah:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    image: savannah-image
    volumes:
      - .:/usr/savannah
    depends_on:
      - database

    stdin_open: true
    tty: true
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
      - DB_NAME=postgres
      - DB_PASS=postgres
      - DB_USER=postgres
      - DB_HOST=database
      - DB_PORT=5432
    networks:
      - back-end

  # proxy:
  #   build:
  #     context: .
  #     dockerfile: nginx/nginx.Dockerfile
  #   image: nginx-custom
  #   ports:
  #     - "80:80"
  #   networks:
  #     - back-end
  #   depends_on:
  #     - savannah
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./app/static:/static
  #   restart: always
volumes:
  pgdata:

networks:
  back-end: