#Build test and deployment Workflow

name: Test and Deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "*"
  pull_request:
    branches: [develop, main]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432
    env:
      DB_NAME: postgres
      DB_USER: postgres
      DB_HOST: localhost
      DB_PASS: postgres
      SECRET_KEY: "rueithgtorhgotrg"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: coverage run manage.py test --verbosity=2 && coverage report -m

