#Build test and deployment Workflow

name: Test and Deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - "*"
  pull_request:
    branches: [develop, main]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        ports:
          - 5432:5432
    env:
      DB_NAME: postgres
      DB_USER: postgres
      DB_HOST: localhost
      DB_PASS: postgres
      SECRET_KEY: "rueithgtorhgotrg"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: coverage run manage.py test --verbosity=2 && coverage report -m

  deploy-prod:
    needs: [tests]
    runs-on: ubuntu-latest
    # if: github.ref_name == 'main'

    steps:
      - name: Checkout Source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          application_name: savannah
          environment_name: Savannah-env

          version_label: ${{ github.sha }}
          region: "ap-northeast-1"
          deployment_package: deploy.zip
